name: Update Recent Activity

on:
  push:
    branches: [main]
  schedule:
    # 北京时间 9:00
    - cron: "0 1 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Recent Activity
        uses: Cloud-WebIDE/group-github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAMES: "Cecil0o0, yiliang114, harbin1053020115"
          GH_REPOS: "microsoft/vscode, microsoft/vscode-l10n, microsoft/vscode-test-web, coder/code-server, eclipse-theia/theia, opensumi/core, opensumi/ide-startup-lite, joyceerhl/vscode-pyolite"
